### ISSUE TITLE
Error while debbuging

### ISSUE THREAD

**Issue by Ahmedjk4** [3imed-jaberi/12-from-to-24-hours#1]
(node:11104) UnhandledPromiseRejectionWarning: TypeError: _12FromTo24Hours is not a function
    at h:\Kira-Bot\Test\index.js:600:1
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by 3imed-jaberi** [comment]
@Arrows12-kira, can you provide an example of your code.
Also, I like to notice you that `12-from-to-24-hours` don't use any promise.
So, you can use any behave that solve the `UnhandledPromiseRejectionWarning`.
  - https://www.npmjs.com/package/make-promises-safe
  - https://www.npmjs.com/package/trace-unhandled
